#!/bin/bash
rsync -av --delete _build/html/ euetitlsi:public_html/edoo/doc
scp -F ssh_config _build/latex/EDOO_Doc.pdf euetitlsi:public_html/edoo/doc
pushd _build
zip -r ../EDOO_Doc_HTML.zip html/
popd
scp EDOO_Doc_HTML.zip euetitlsi:public_html/edoo/doc
