#!/bin/bash
rsync -av --delete _build/html/ euetit@login1.lsi.upc.edu:public_html/pbd/apunts
scp _build/latex/Apunts_PBD.pdf euetit@login1.lsi.upc.edu:public_html/pbd/apunts
pushd _build
zip -r ../Apunts_PBD_HTML.zip html/
popd
scp Apunts_PBD_HTML.zip euetit@login1.lsi.upc.edu:public_html/pbd/apunts
